### ISSUE TITLE
无法运行程序

### ISSUE THREAD

**Issue by hzdu** [NaiboWang/EasySpider#124]
我的本地环境是 windows11 x64+Anaconda（默认Python版本是3.10.9)
设计好任务启用任务后错误提示如下：
Configurations:
+------------------+------+------------------------------+
|       Key        | Type | Value                        |
+------------------+------+------------------------------+
|        id        | list | [5]                          |
| saved_file_name  | str  |                              |
|    user_data     | bool | False                        |
|  config_folder   | str  | E:/greensoftware/EasySpider/ |
| config_file_name | str  | config.json                  |
|    read_type     | str  | remote                       |
|     headless     | bool | False                        |
|  server_address  | str  | http://localhost:8074        |
|     version      | str  | 0.3.5                        |
+------------------+------+------------------------------+

win32 ('64bit', 'WindowsPE')
Finding chromedriver in EasySpider E:\greensoftware\EasySpider/EasySpider
Chrome location: E:\greensoftware\EasySpider\EasySpider/resources/app/chrome_win64/chrome.exe
Chromedriver location: E:\greensoftware\EasySpider\EasySpider/resources/app/chrome_win64/chromedriver_win64.exe
Config file path: E:/greensoftware/EasySpider/config.json

Absolute_user_data_folder: D:\Document\Projects\EasySpider\ElectronJS\user_data

id:  5
remote
Task Name: JJ's House
任务名称: JJ's House
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1581, in <module>
  File "myChrome.py", line 26, in __init__
  File "selenium\webdriver\chrome\webdriver.py", line 69, in __init__
  File "selenium\webdriver\chromium\webdriver.py", line 93, in __init__
  File "selenium\webdriver\chromium\remote_connection.py", line 29, in __init__
  File "selenium\webdriver\remote\remote_connection.py", line 191, in __init__
  File "selenium\webdriver\remote\remote_connection.py", line 162, in _get_connection_manager
  File "urllib3\poolmanager.py", line 481, in __init__
urllib3.exceptions.ProxySchemeUnknown: Proxy URL had no scheme, should start with http:// or https://
[19020] Failed to execute script 'easyspider_executestage' due to unhandled exception!

因为我需要抓取的网站需要翻墙，本地使用Clash的Service Mode进行了全局的。

**Comment by NaiboWang** [comment]
首先就是和自己什么python环境无关；
另外就是你的代理似乎设置的有问题，参考：https://zhuanlan.zhihu.com/p/457873871?utm_id=0

最后就是不行不要用全局代理，用局部代理，浏览器配合Proxy SwitchyOmega插件使用。

**Comment by hzdu** [comment]
我到一个干净的系统上不使用代理，依旧会出现上面的错误，根据错误信息，可能是程序自带的Python版本大于3.7造成的urllib3错误

**Comment by NaiboWang** [comment]
如果是这样，可以自己下载个低版本的python然后下载源码自行编译运行。
