### ISSUE TITLE
0.5.0 Pre-release一直编译失败

### ISSUE THREAD

**Issue by ellieot** [NaiboWang/EasySpider#149]
有没有大佬发一份64的编译后文件，请喝咖啡，收到之后我删issue

**Comment by ellieot** [comment]
折腾完，编译成功了，不麻烦大佬们了close issue

**Comment by ellieot** [comment]
执行命令run package出错：

D:\EasySpider-0.5.0\ElectronJS>npm run package

> easy-spider@0.5.0 package D:\EasySpider-0.5.0\ElectronJS
> electron-forge package

√ Checking your system
√ Preparing to package application
√ Running packaging hooks
  √ Running generateAssets hook
  √ Running prePackage hook
> Packaging application
  › Determining targets...
  > Packaging for x64 on win32
    √ Copying files
    | Preparing native dependencies: 0 / 1
    ■ Finalizing package
■ Running postPackage hook

› �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: �м�Ŀ¼�����Ŀ¼�޷�פ����…
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: ָ���������ִ���ļ���CL.…
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� System.IO.__Err …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� System.IO.FileS …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� System.IO.FileS …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003:    �� Microsoft.Build …
  Error: `H:\visual_studio\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
      at ChildProcess.onExit (D:…

An unhandled rejection has occurred inside Forge:
Error: node-gyp failed to rebuild 'H:\temp\electron-packager\win32-x64\EasySpider-win32-x64-X0rlD1\resources\app\node_modules\extract-file-icon'
at ChildProcess.<anonymous> (D:\EasySpider-0.5.0\ElectronJS\node_modules\@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:118:24)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! easy-spider@0.5.0 package: `electron-forge package`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the easy-spider@0.5.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2023-08-01T22_18_54_517Z-debug.log

**Comment by ellieot** [comment]
能不能打包个docker或者发布一下release，弄一天一夜了呜呜呜，真的努力尝试也去网上搜资料了，实在是解决不了

**Comment by NaiboWang** [comment]
> 执行命令run package出错：
> 
> D:\EasySpider-0.5.0\ElectronJS>npm run package
> 
> > easy-spider@0.5.0 package D:\EasySpider-0.5.0\ElectronJS
> > electron-forge package
> 
> √ Checking your system √ Preparing to package application √ Running packaging hooks √ Running generateAssets hook √ Running prePackage hook
> 
> > Packaging application
> > › Determining targets...
> > Packaging for x64 on win32
> > √ Copying files
> > | Preparing native dependencies: 0 / 1
> > ■ Finalizing package
> > ■ Running postPackage hook
> 
> › �ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء� H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: �м�Ŀ¼�����Ŀ¼�޷�פ����… H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: ָ���������ִ���ļ���CL.… H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� System.IO.__Err … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� System.IO.FileS … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� System.IO.FileS … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … H:\visual_studio\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(734,5): error MSB6003: �� Microsoft.Build … Error: `H:\visual_studio\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1 at ChildProcess.onExit (D:…
> 
> An unhandled rejection has occurred inside Forge: Error: node-gyp failed to rebuild 'H:\temp\electron-packager\win32-x64\EasySpider-win32-x64-X0rlD1\resources\app\node_modules\extract-file-icon' at ChildProcess. (D:\EasySpider-0.5.0\ElectronJS\node_modules@electron\rebuild\lib\module-type\node-gyp\node-gyp.js:118:24) at ChildProcess.emit (events.js:400:28) at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12) npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! easy-spider@0.5.0 package: `electron-forge package` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the easy-spider@0.5.0 package script. npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in: npm ERR! C:\Users\Administrator\AppData\Roaming\npm-cache_logs\2023-08-01T22_18_54_517Z-debug.log

Readme文件里写了如果是windows需要安装VS Build Tools，你应该是没有安装。

**Comment by NaiboWang** [comment]
EasySpider 0.5.0 x64 Beta版本已发布，欢迎试用。
