### ISSUE TITLE
Centos环境，下载0.3.5版本的源码编译时，出错

### ISSUE THREAD

**Issue by Gzj369** [NaiboWang/EasySpider#170]
![image](https://github.com/NaiboWang/EasySpider/assets/13391430/ad53d437-8e3f-4ce9-a18b-1999cc2a62ec)

按照指导，**第1步 编译浏览器扩展，执行npm install时**出现如下错误：

[xx@LIN-5AB42623370 manifest_v3]$ npm install

> playwright-chromium@1.27.1 install /home/xx/文档/Software/爬取数据/EasySpider-0.3.5/Extension/manifest_v3/node_modules/playwright-chromium
> node install.js

BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
Error: write EPROTO 140577233288128:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}
Error: write EPROTO 140656452144064:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}
Error: write EPROTO 140163944864704:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16) {
  errno: 'EPROTO',
  code: 'EPROTO',
  syscall: 'write'
}
(node:277158) UnhandledPromiseRejectionWarning: Error: Failed to download Chromium 107.0.5304.18 (playwright build v1028), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/home/xx/文档/Software/爬取数据/EasySpider-0.3.5/Extension/manifest_v3/node_modules/playwright-chromium/node_modules/playwright-core/lib/server/registry/download.js:51:16)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
    at /home/xx/文档/Software/爬取数据/EasySpider-0.3.5/Extension/manifest_v3/node_modules/playwright-chromium/node_modules/playwright-core/lib/server/registry/index.js:709:13
    at async Registry._downloadExecutable (/home/xx/文档/Software/爬取数据/EasySpider-0.3.5/Extension/manifest_v3/node_modules/playwright-chromium/node_modules/playwright-core/lib/server/registry/index.js:708:5)
    at async Registry.install (/home/xx/文档/Software/爬取数据/EasySpider-0.3.5/Extension/manifest_v3/node_modules/playwright-chromium/node_modules/playwright-core/lib/server/registry/index.js:672:9)
    at async installBrowsersForNpmInstall (/home/xx/文档/Software/爬取数据/EasySpider-0.3.5/Extension/manifest_v3/node_modules/playwright-chromium/node_modules/playwright-core/lib/server/registry/index.js:876:3)
(node:277158) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:277158) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

我的**node版本为12.12.0** ，麻烦大佬帮忙看看 @NaiboWang

**Comment by NaiboWang** [comment]
可跳过浏览器扩展部分的编译，使用`ElectronJS`文件夹下直接编译好的`EasySpider_zh.crx`文件即可。
