### ISSUE TITLE
Mac OS 13.6 执行任务中报错

### ISSUE THREAD

**Issue by binyellow** [NaiboWang/EasySpider#210]
```
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1957, in <module>
  File "myChrome.py", line 26, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 69, in __init__
  File "selenium/webdriver/chromium/webdriver.py", line 92, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 272, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 364, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 429, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 243, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location EasySpider.app/Contents/Resources/app/chrome_mac64.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
0   chromedriver_mac64                  0x00000001044f665c chromedriver_mac64 + 4318812
1   chromedriver_mac64                  0x00000001044eed00 chromedriver_mac64 + 4287744
2   chromedriver_mac64                  0x00000001041207ec chromedriver_mac64 + 296940
3   chromedriver_mac64                  0x000000010414ada8 chromedriver_mac64 + 470440
4   chromedriver_mac64                  0x0000000104147ca0 chromedriver_mac64 + 457888
5   chromedriver_mac64                  0x0000000104187954 chromedriver_mac64 + 719188
6   chromedriver_mac64                  0x0000000104187120 chromedriver_mac64 + 717088
7   chromedriver_mac64                  0x0000000104152178 chromedriver_mac64 + 500088
8   chromedriver_mac64                  0x0000000104152fc0 chromedriver_mac64 + 503744
9   chromedriver_mac64                  0x00000001044b6c40 chromedriver_mac64 + 4058176
10  chromedriver_mac64                  0x00000001044bb160 chromedriver_mac64 + 4075872
11  chromedriver_mac64                  0x000000010447ee68 chromedriver_mac64 + 3829352
12  chromedriver_mac64                  0x00000001044bbc4c chromedriver_mac64 + 4078668
13  chromedriver_mac64                  0x0000000104493f08 chromedriver_mac64 + 3915528
14  chromedriver_mac64                  0x00000001044d8140 chromedriver_mac64 + 4194624
15  chromedriver_mac64                  0x00000001044d82c4 chromedriver_mac64 + 4195012
16  chromedriver_mac64                  0x00000001044e84d0 chromedriver_mac64 + 4261072
17  libsystem_pthread.dylib             0x000000018fbe7fa8 _pthread_start + 148
18  libsystem_pthread.dylib             0x000000018fbe2da0 thread_start + 8

[21731] Failed to execute script 'easyspider_executestage' due to unhandled exception!
```

**Comment by NaiboWang** [comment]
参考：
https://github.com/NaiboWang/EasySpider/issues/181

**Comment by binyellow** [comment]
按照步骤更新chromedriver后，仍然有报错
```
In this mode, task ID 40 will start from the beginning, if you want to start from the last step, please set the option 'start from the last step' to 'yes' when saving the task.
Loading stealth.min.js
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1977, in <module>
  File "easyspider_executestage.py", line 152, in __init__
KeyError: 'links'
[39242] Failed to execute script 'easyspider_executestage' due to unhandled exception!
```
而且我的浏览器不会闪退，是打开后无反应，然后命令行就报上面的错误了

我的系统信息
1. MacOS 13.6
2. EasySpider打开的Chrome版本 117.0.5938.149

**Comment by binyellow** [comment]
重新设计任务后不报错了，但是旧的任务仍然有报错
```
In this mode, task ID 40 will start from the beginning, if you want to start from the last step, please set the option 'start from the last step' to 'yes' when saving the task.
Loading stealth.min.js
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1977, in <module>
  File "easyspider_executestage.py", line 152, in __init__
KeyError: 'links'
[39242] Failed to execute script 'easyspider_executestage' due to unhandled exception!
```

这种case感觉大佬可以放到wiki中，我是从你[其他的issue回答中](https://github.com/NaiboWang/EasySpider/issues/186#:~:text=%E5%8F%AF%E8%83%BD%E5%B7%B2%E7%BB%8F%E8%BF%87%E6%97%B6%EF%BC%8C-,%E5%8F%AF%E4%BB%A5%E5%B0%9D%E8%AF%95%E8%87%AA%E5%B7%B1%E8%AE%BE%E8%AE%A1%E4%B8%80%E4%B8%AA%E7%AE%80%E5%8D%95%E4%BB%BB%E5%8A%A1%E8%AF%95%E4%B8%80%E8%AF%95,-%EF%BC%8C%E8%BF%99%E5%B1%9E%E4%BA%8E%E6%9C%80)看到的

**Comment by NaiboWang** [comment]
旧任务可能因为版本问题无法执行，自己设计的任务能够执行即可。
感谢建议，Issues和Wiki都是大家看文档的方式，会逐步完善文档。
