### ISSUE TITLE
请问如果我想docker部署执行阶段要怎么做呢

### ISSUE THREAD

**Issue by HHR-learner** [NaiboWang/EasySpider#232]
1、现在想在本地用win版本的设计任务，然后通过api传execution_instances文件进docker部署的服务器使用，所以只需要执行模块在docker里就可以了，这个需要怎么做呢。
2、或者我可以通过在源码里直接执行easyspider_executestage.py来执行任务吗，如果可以的话似乎可以直接把执行阶段的源码打包进docker就好了？
3、我下载了0.3.5的linux版本去试着运行了一下，结果报错了：

```
Traceback (most recent call last):
  File "easyspider_executestage.py", line 1501, in <module>
  File "myChrome.py", line 25, in __init__
  File "selenium/webdriver/chrome/webdriver.py", line 69, in __init__
  File "selenium/webdriver/chromium/webdriver.py", line 92, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 272, in __init__
  File "selenium/webdriver/remote/webdriver.py", line 364, in start_session
  File "selenium/webdriver/remote/webdriver.py", line 429, in execute
  File "selenium/webdriver/remote/errorhandler.py", line 243, in check_response
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /data/HuHR/EasySpider_Linux_x64/EasySpider/resources/app/chrome_linux64/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55da3af1c133 <unknown>
#1 0x55da3ac50966 <unknown>
#2 0x55da3ac7a21a <unknown>
#3 0x55da3ac7607b <unknown>
#4 0x55da3acb59ad <unknown>
#5 0x55da3acb518f <unknown>
#6 0x55da3acac9a3 <unknown>
#7 0x55da3ac8146a <unknown>
#8 0x55da3ac8255e <unknown>
#9 0x55da3aedbcae <unknown>
#10 0x55da3aedf8fe <unknown>
#11 0x55da3aee8f20 <unknown>
#12 0x55da3aee0923 <unknown>
#13 0x55da3aeb3c0e <unknown>
#14 0x55da3af03b08 <unknown>
#15 0x55da3af03c97 <unknown>
#16 0x55da3af14113 <unknown>
#17 0x7fd1c405a609 start_thread

[2324134] Failed to execute script 'easyspider_executestage' due to unhandled exception!
```

**Comment by NaiboWang** [comment]
1、现在想在本地用win版本的设计任务，然后通过api传execution_instances文件进docker部署的服务器使用，所以只需要执行模块在docker里就可以了，这个需要怎么做呢。

这个做法是可以的，你可以手动复制execution_instances文件夹里的json文件到docker的execution_instances文件夹，然后命令行执行时传入对应的ID号即可，ID号即json文件的名称。

2、或者我可以通过在源码里直接执行easyspider_executestage.py来执行任务吗，如果可以的话似乎可以直接把执行阶段的源码打包进docker就好了？

可以，请参考Readme.md中的介绍进行打包，主要是chromedriver，chrome位置的配置，各个插件和必备js文件的配置以及Python各种包的配置。

3、我下载了0.3.5的linux版本去试着运行了一下，结果报错了。

Linux版本只适用于Ubuntu等系统，并且我打包的版本需要配合图形界面使用，我自己执行并没有问题，你的问题大概率是chrome程序无法运行在你的系统上，建议自行使用自己环境下能够使用的chrome进行打包运行。

**Comment by HHR-learner** [comment]
> 1、现在想在本地用win版本的设计任务，然后通过api传execution_instances文件进docker部署的服务器使用，所以只需要执行模块在docker里就可以了，这个需要怎么做呢。
> 
> 这个做法是可以的，你可以手动复制execution_instances文件夹里的json文件到docker的execution_instances文件夹，然后命令行执行时传入对应的ID号即可，ID号即json文件的名称。
> 
> 2、或者我可以通过在源码里直接执行easyspider_executestage.py来执行任务吗，如果可以的话似乎可以直接把执行阶段的源码打包进docker就好了？
> 
> 可以，请参考Readme.md中的介绍进行打包，主要是chromedriver，chrome位置的配置，各个插件和必备js文件的配置以及Python各种包的配置。
> 
> 3、我下载了0.3.5的linux版本去试着运行了一下，结果报错了。
> 
> Linux版本只适用于Ubuntu等系统，并且我打包的版本需要配合图形界面使用，我自己执行并没有问题，你的问题大概率是chrome程序无法运行在你的系统上，建议自行使用自己环境下能够使用的chrome进行打包运行。

目前正在针对2进行运行尝试，在更改了chrome、chromedriver位置，以及取消了XPathHelper插件的运用后，已经可以在本地仅使用ExecuteStage文件夹与chrome_win64（EasySpider文件夹里只有这个文件夹，没有其他的node_modules等文件夹）文件夹的情况下成功运行例子（打开百度，采集网页标题）。
![image](https://github.com/NaiboWang/EasySpider/assets/74774809/3b10ff7b-b390-40ce-a4aa-106cefc87b02)
下一步准备在docker中部署可以使用的chrome与chromedriver，目前有两个疑问

1、这样的运行操作会导致某些bug或者报错吗
2、0.3.5版本的chrome_linux64内的文件是仅为了保证有chrome和chromedriver吗，我直接在docker里下载其他的，再修改我的路径是不是一样的效果，有版本要求吗，或者仅版本相同即可

**Comment by HHR-learner** [comment]
> 最开始开发的目的是“Easy”是想让许多没有代码基础的人可以打开即用的，没想到会有许多会用Linux，甚至会用Docker的人来用，以后可以做一个docker镜像，很简单，因为程序本身就是自己建立了一个Web浏览器。 你下载好Linux版本的程序打开以后，其他机器就可以通过http://IP地址:8074 来访问服务器，通过修改`config.json`里的服务器配置可以修改端口号和云服务器地址。

_Originally posted by @NaiboWang in https://github.com/NaiboWang/EasySpider/issues/27#issuecomment-1566019748_

另外关于这个我也有些疑问，其他机器可以通过这个端口来访问服务器，那设计流程的窗口也会在其他机器弹出来吗

**Comment by NaiboWang** [comment]
在远程机器打开easyspider后，本地机器通过修改config.json文件中的服务器地址和端口号可以直接在本地设计完成流程后，直接将任务保存在远程服务器，调用的时候也是远程调用。
设计流程时浏览器在本地弹出，这里的远程是指任务信息的读取和保存在远程，不在本地。

**Comment by NaiboWang** [comment]
> > 1、现在想在本地用win版本的设计任务，然后通过api传execution_instances文件进docker部署的服务器使用，所以只需要执行模块在docker里就可以了，这个需要怎么做呢。
> 
> > 
> 
> > 这个做法是可以的，你可以手动复制execution_instances文件夹里的json文件到docker的execution_instances文件夹，然后命令行执行时传入对应的ID号即可，ID号即json文件的名称。
> 
> > 
> 
> > 2、或者我可以通过在源码里直接执行easyspider_executestage.py来执行任务吗，如果可以的话似乎可以直接把执行阶段的源码打包进docker就好了？
> 
> > 
> 
> > 可以，请参考Readme.md中的介绍进行打包，主要是chromedriver，chrome位置的配置，各个插件和必备js文件的配置以及Python各种包的配置。
> 
> > 
> 
> > 3、我下载了0.3.5的linux版本去试着运行了一下，结果报错了。
> 
> > 
> 
> > Linux版本只适用于Ubuntu等系统，并且我打包的版本需要配合图形界面使用，我自己执行并没有问题，你的问题大概率是chrome程序无法运行在你的系统上，建议自行使用自己环境下能够使用的chrome进行打包运行。
> 
> 
> 
> 目前正在针对2进行运行尝试，在更改了chrome、chromedriver位置，以及取消了XPathHelper插件的运用后，已经可以在本地仅使用ExecuteStage文件夹与chrome_win64（EasySpider文件夹里只有这个文件夹，没有其他的node_modules等文件夹）文件夹的情况下成功运行例子（打开百度，采集网页标题）。
> 
> ![image](https://github.com/NaiboWang/EasySpider/assets/74774809/3b10ff7b-b390-40ce-a4aa-106cefc87b02)
> 
> 下一步准备在docker中部署可以使用的chrome与chromedriver，目前有两个疑问
> 
> 
> 
> 1、这样的运行操作会导致某些bug或者报错吗
> 
> 2、0.3.5版本的chrome_linux64内的文件是仅为了保证有chrome和chromedriver吗，我直接在docker里下载其他的，再修改我的路径是不是一样的效果，有版本要求吗，或者仅版本相同即可

1. 不会有问题。

2.浏览器和driver版本一致即可。

欢迎做好docker镜像后在这里分享给其他有需要的朋友。

**Comment by HHR-learner** [comment]
目前仍然在尝试。。被docker弄的半死不活，明明在系统里可以运行，打进容器里却总是报错，这个dbus模块是用来干啥的，可以禁用它吗
`[46:1110/034540.685597:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
[46:1110/034540.685688:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: Connection refused
[46:1110/034540.686567:VERBOSE1:pref_proxy_config_tracker_impl.cc(187)] 0x285800302600: set chrome proxy config service to 0x285800339e80
[46:1110/034540.686931:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[46:1110/034540.686974:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[46:1110/034540.686984:VERBOSE1:select_file_dialog_linux_portal.cc(248)] File chooser portal available: no
[46:1110/034540.728643:VERBOSE1:media_stream_manager.cc(923)] MSM::InitializeMaybeAsync([this=0x285800317680])
[46:1110/034540.728684:VERBOSE1:media_stream_manager.cc(923)] MDM::MediaDevicesManager()
[46:1110/034540.728701:VERBOSE1:media_stream_manager.cc(923)] MSM::MediaStreamManager([this=0x285800317680]))
[76:1110/034540.734899:VERBOSE1:va_stubs.cc(734)] dlopen(libva.so.2) failed.
[76:1110/034540.735040:VERBOSE1:va_stubs.cc(736)] dlerror() says:
libva.so.2: cannot open shared object file: No such file or directory
[76:1110/034540.735167:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is disabled, ANGLE is`

**Comment by NaiboWang** [comment]
8075端口用于在设计阶段的GUI中从Excel文件读取输入参数，如果用不到这个功能可以屏蔽掉此端口。
