### ISSUE TITLE
多网址、多任务、网页空白

### ISSUE THREAD

**Issue by pavilion2002** [NaiboWang/EasySpider#251]
作者您好
1.怎么设置网页在正确进入页面前每间隔一定时间就刷新，（有时候新的网页进不去并显示空白，但是刷新一下就好了）。
2.如果报错可以设置跳过这一条网址，或者回退吗。

真的非常感谢。
例如这样：
![image](https://github.com/NaiboWang/EasySpider/assets/73059175/4f62284f-ec66-4809-8915-6223f6e4466f)

我的报错：
Exception in thread Thread-4:
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "easyspider_executestage.py", line 351, in run
  File "easyspider_executestage.py", line 739, in executeNode
  File "easyspider_executestage.py", line 748, in executeNode
  File "easyspider_executestage.py", line 1715, in getData
  File "myChrome.py", line 60, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 856, in find_element
  File "selenium\webdriver\remote\webdriver.py", line 429, in execute
  File "selenium\webdriver\remote\errorhandler.py", line 243, in check_response
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//body"}
  (Session info: chrome=115.0.5790.171)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00007FF76DB44A62+57106]
        (No symbol) [0x00007FF76DABCF52]
        (No symbol) [0x00007FF76D98E2CB]
        (No symbol) [0x00007FF76D9C786E]
        (No symbol) [0x00007FF76D9C795C]
        (No symbol) [0x00007FF76DA00477]
        (No symbol) [0x00007FF76D9E69FF]
        (No symbol) [0x00007FF76D9FE522]
        (No symbol) [0x00007FF76D9E6793]
        (No symbol) [0x00007FF76D9BCE81]
        (No symbol) [0x00007FF76D9BE064]
        GetHandleVerifier [0x00007FF76DDF4222+2873042]
        GetHandleVerifier [0x00007FF76DE46590+3209792]
        GetHandleVerifier [0x00007FF76DE3F3AF+3180639]
        GetHandleVerifier [0x00007FF76DBD5F25+652245]
        (No symbol) [0x00007FF76DAC8618]
        (No symbol) [0x00007FF76DAC47C4]
        (No symbol) [0x00007FF76DAC48BC]
        (No symbol) [0x00007FF76DAB4C33]
        BaseThreadInitThunk [0x00007FF8AE4E7344+20]
        RtlUserThreadStart [0x00007FF8AF3826B1+33]

**Comment by pavilion2002** [comment]
简单版：怎么设置网页在正确进入页面前每间隔一定时间就刷新，（有时候新的网页进不去并显示空白，但是刷新一下就好了）。
上面写的太麻烦了

**Comment by NaiboWang** [comment]
添加条件分支，当页面包含//body节点时执行你自己的操作，否则执行刷新页面操作，示例JSON文件，可直接放入tasks文件夹内读取：

[255.json](https://github.com/NaiboWang/EasySpider/files/13638750/255.json)

![image](https://github.com/NaiboWang/EasySpider/assets/30287768/24ac36c4-6446-4cb6-9d39-f284b6723a47)


另外过几天将发布新版本，此Bug将会被修复。
