### ISSUE TITLE
Ubuntu 24.04 系统上运行易采集遇到的问题

### ISSUE THREAD

**Issue by liuyong240** [NaiboWang/EasySpider#405]
操作系统：Ubuntu 24.04 LTS Desktop
EasySpider 版本:  0.6.2
操作步骤：
   1. 打开主体
   2. 点击中文
   3. 选择设计模式 -> 使用纯净版浏览器设计
   4. 出现如下错误信息
   
错误信息：
[6201:0527/174443.007813:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[6201:0527/174445.868186:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[6201:0527/174445.879655:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
set socket_flowchart at time:  2024-05-27T09:44:56.350Z
(node:6163) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/chrome_linux64/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(Use `EasySpider --trace-warnings ...` to show where the warning was created)
(node:6163) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6163) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/chrome_linux64/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
    at Object.throwDecodedError (/home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/node_modules/selenium-webdriver/lib/error.js:524:15)
    at parseHttpResponse (/home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/node_modules/selenium-webdriver/lib/http.js:601:13)
    at Executor.execute (/home/hujing/spider/easy-spider/EasySpider_Linux_x64_bak/EasySpider/resources/app/node_modules/selenium-webdriver/lib/http.js:529:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
(node:6163) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)

**Comment by dadalongvs** [comment]
我现在centos上编译完运行npm run start_direct也是报这个错误，原来你ubuntu上也会有。。。
![image](https://github.com/NaiboWang/EasySpider/assets/108457248/d87ab451-8d34-4468-8380-283696880666)

**Comment by liuyong240** [comment]
The problem has been solved. Problem cause: chrome driver folder permissions issue

**Comment by zrbcode** [comment]
怎么解决的？给了777权限还是不行

**Comment by NaiboWang** [comment]
【无代码可视化爬虫EasySpider：从源代码编译程序并设计运行和调试任务指南（基于Ubuntu24.04）-哔哩哔哩】 https://b23.tv/ypav1R5

看下这个视频
