### ISSUE TITLE
Mac10.15.7 python3.9编译0.6.2出错，请帮助。

### ISSUE THREAD

**Issue by Kai-0** [NaiboWang/EasySpider#455]
(EasySpider-venv) kai@kaideMacBook-Pro executestage % python easyspider_executestage.py --ids '[3]' --user_data 0 --server_address http://localhost:8074 --config_folder "./" --headless 0 --read_type remote --config_file_name config.json --saved_file_name 

Configurations:
+------------------+------+-----------------------+
|       Key        | Type | Value                 |
+------------------+------+-----------------------+
|       ids        | list | [3]                   |
| saved_file_name  | str  |                       |
|    user_data     | bool | False                 |
|  config_folder   | str  | ./                    |
| config_file_name | str  | config.json           |
|    read_type     | str  | remote                |
|     headless     | bool | False                 |
|  server_address  | str  | http://localhost:8074 |
|     keyboard     | bool | True                  |
|    pause_key     | str  | p                     |
|     version      | str  | 0.6.2                 |
|  docker_driver   | str  |                       |
+------------------+------+-----------------------+

darwin ('64bit', '')
Traceback (most recent call last):
  File "/Users/kai/Documents/Dev/EasySpider-venv/ExecuteStage/easyspider_executestage.py", line 2233, in <module>
    options.add_extension(
  File "/Users/kai/Documents/Dev/EasySpider-venv/lib/python3.9/site-packages/selenium/webdriver/chromium/options.py", line 101, in add_extension
    raise OSError("Path to the extension doesn't exist")
OSError: Path to the extension doesn't exist

**Comment by zhaoyajie1011** [comment]
我也遇到了同样的问题：

**Comment by zhaoyajie1011** [comment]
./easyspider_executestage --ids '[0]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/xxx/Library/Application\ Support/EasySpider/" --headless 0 --read_type local --config_file_name config.json --saved_file_name /Users/xxx/Downloads/111111.txt
OCR识别无法在当前环境下使用（ddddocr库缺失），请使用完整版执行器easyspider_executestage_full来运行需要OCR识别的任务。
OCR recognition cannot be used in the current environment (ddddocr library is missing), please use the executor with ddddocr 'easyspider_executestage_full' to run the task which requires OCR recognition.
数据去重无法在当前环境下使用（pandas库缺失），请使用完整版执行器easyspider_executestage_full来运行需要去重的任务。
Data deduplication cannot be used in the current environment (pandas library is missing), please use the executor with pandas 'easyspider_executestage_full' to run the task which requires data deduplication.

Configurations:
+------------------+------+-----------------------------------------------------------+
|       Key        | Type | Value                                                     |
+------------------+------+-----------------------------------------------------------+
|       ids        | list | [0]                                                       |
| saved_file_name  | str  | /Users/xxx/Downloads/111111.txt                     |
|    user_data     | bool | False                                                     |
|  config_folder   | str  | /Users/xxx/Library/Application\ Support/EasySpider/ |
| config_file_name | str  | config.json                                               |
|    read_type     | str  | local                                                     |
|     headless     | bool | False                                                     |
|  server_address  | str  | http://localhost:8074                                     |
|     keyboard     | bool | True                                                      |
|    pause_key     | str  | p                                                         |
|     version      | str  | 0.6.2                                                     |
+------------------+------+-----------------------------------------------------------+


Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip:
pip index versions commandline_config
pip install commandline --upgrade
darwin ('64bit', '')
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2266, in <module>
  File "selenium/webdriver/chromium/options.py", line 101, in add_extension
OSError: Path to the extension doesn't exist
[10427] Failed to execute script 'easyspider_executestage' due to unhandled exception!

**Comment by zhaoyajie1011** [comment]
![image](https://github.com/NaiboWang/EasySpider/assets/38313532/b7a39b49-9711-44a7-87be-bb9a2f70d67f)

**Comment by NaiboWang** [comment]
下载一个能用的EasySpider，把它放到ExecuteStage文件夹里再试试。

**Comment by stardustliu** [comment]
请问大家这个问题是如何解决的？
我看代码是easyspider_executestage.py的2197行报错：
`options.add_extension(
            "EasySpider.app/Contents/Resources/app/XPathHelper.crx")`
  是要去加载EasySpider的一个资源，但是我是想通过docker进行源码安装，这个时候系统中还没有EasySpider呢。

**Comment by Xuepei-W** [comment]
请问大家，这个问题解决了吗，我这边也遇到了一样的问题。
 
设备：MacBook Air 13   ARM

问题描述：执行设计好的任务时，提示需在终端拷贝和运行以下命令“cd /Users/sarah/Downloads/EasySpider_MacOS
./easyspider_executestage --ids '[5]' --user_data 1 --server_address http://localhost:8074 --config_folder "/Users/sarah/Library/Application Support/EasySpider/" --headless 0 --read_type local --config_file_name config.json --saved_file_name ”

运行命令后报以下错误：Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
darwin ('64bit', '')
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2266, in <module>
  File "selenium/webdriver/chromium/options.py", line 101, in add_extension
OSError: Path to the extension doesn't exist
[13612] Failed to execute script 'easyspider_executestage' due to unhandled exception!

求教如何解决，感谢！

**Comment by 7zq7** [comment]
add one 
Traceback (most recent call last):
  File "easyspider_executestage.py", line 2266, in <module>
  File "selenium/webdriver/chromium/options.py", line 101, in add_extension
OSError: Path to the extension doesn't exist
[21324] Failed to execute script 'easyspider_executestage' due to unhandled exception!
