### ISSUE TITLE
如何每隔一段时间执行一次任务

### ISSUE THREAD

**Issue by zhanmeihe** [NaiboWang/EasySpider#489]
如何每隔一段时间执行一次任务？

**Comment by NaiboWang** [comment]
参考：https://github.com/NaiboWang/EasySpider/issues/22

**Comment by jinbagua** [comment]
请问一下，我在linux系统下设置了定时任务但是执行失败，应如何解决？
![微信截图_20240902084837](https://github.com/user-attachments/assets/fb841424-d763-4e00-a956-f857299c1f44)
错误信息如下：
Traceback (most recent call last):
  File "easyspider_executestage.py", line 34, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 385, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 76, in backend
ImportError: this platform is not supported: ('failed to acquire X connection: Bad display name ""', DisplayNameError(''))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[267962] Failed to execute script 'easyspider_executestage' due to unhandled exception!
