### ISSUE TITLE
mac 出现各种报错，麻烦作者大大看一下

### ISSUE THREAD

**Issue by billgrandon** [NaiboWang/EasySpider#77]
Last login: Sun Jun 11 18:35:02 on ttys000
bill@billdeMacBook-Pro ~ % cd /Users/bill/Downloads/EasySpider_MacOS_all_arch
./easyspider_executestage --id '[7]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/" --headless 0 --read_type remote --config_file_name config.json --saved_file_name 
Traceback (most recent call last):
  File "commandline_config/commandline_config.py", line 164, in convert_type
  File "<string>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "easyspider_executestage.py", line 688, in <module>
  File "commandline_config/commandline_config.py", line 107, in __init__
  File "commandline_config/commandline_config.py", line 139, in set_command_line
  File "commandline_config/commandline_config.py", line 201, in convert_type
AttributeError: Cannot convert [7] to type int
[1571] Failed to execute script 'easyspider_executestage' due to unhandled exception!

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "easyspider_executestage.py", line 674, in clean
  File "easyspider_executestage.py", line 660, in saveData
TypeError: can only concatenate str (not "NoneType") to str
bill@billdeMacBook-Pro EasySpider_MacOS_all_arch % cd /Users/bill/Downloads/EasySpider_MacOS_all_arch  
./easyspider_executestage --id 7 --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/"   --headless 0  --read_type remote --config_file_name config.json --saved_file_name
The key 'headless' is not exist in your preset configuration dict, please check if you input the correct name.

Traceback (most recent call last):
  File "easyspider_executestage.py", line 688, in <module>
  File "commandline_config/commandline_config.py", line 107, in __init__
  File "commandline_config/commandline_config.py", line 139, in set_command_line
  File "commandline_config/commandline_config.py", line 209, in convert_type
UnboundLocalError: local variable 'variable' referenced before assignment
[1617] Failed to execute script 'easyspider_executestage' due to unhandled exception!

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "easyspider_executestage.py", line 674, in clean
  File "easyspider_executestage.py", line 660, in saveData
TypeError: can only concatenate str (not "NoneType") to str
bill@billdeMacBook-Pro EasySpider_MacOS_all_arch % % cd /Users/bill/Downloads/EasySpider_MacOS_all_arch  
./easyspider_executestage --id 7 --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/"   --headless 0  --read_type remote --config_file_name config.json --saved_file_% cd /Users/bill/Downloads/EasySpider_MacOS_all_arch ./easyspider_executestage --id 7 --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/"  --read_type remote --config_file_name config.json --saved_file_name
fg: no current job
% cd /Users/bill/Downloads/EasySpider_MacOS_all_arch ./easyspider_executestage --id 7 --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/"  --read_type remote --config_file_name config.json --saved_file_name
The key 'headless' is not exist in your preset configuration dict, please check if you input the correct name.

Traceback (most recent call last):
  File "easyspider_executestage.py", line 688, in <module>
  File "commandline_config/commandline_config.py", line 107, in __init__
  File "commandline_config/commandline_config.py", line 139, in set_command_line
  File "commandline_config/commandline_config.py", line 209, in convert_type
UnboundLocalError: local variable 'variable' referenced before assignment
[1630] Failed to execute script 'easyspider_executestage' due to unhandled exception!

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "easyspider_executestage.py", line 674, in clean
  File "easyspider_executestage.py", line 660, in saveData
TypeError: can only concatenate str (not "NoneType") to str
bill@billdeMacBook-Pro EasySpider_MacOS_all_arch % % cd /Users/bill/Downloads/EasySpider_MacOS_all_arch ./easyspider_executestage --id 7 --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/"  --read_type remote --config_file_name config.json --saved_file_name
fg: no current job
bill@billdeMacBook-Pro EasySpider_MacOS_all_arch % cd /Users/bill/Downloads/EasySpider_MacOS_all_arch
./easyspider_executestage --id '[23]' --user_data 0 --server_address http://localhost:8074 --config_folder "/Users/bill/Library/Application Support/EasySpider/" --headless 0 --read_type remote --config_file_name config.json --saved_file_name
Traceback (most recent call last):
  File "commandline_config/commandline_config.py", line 164, in convert_type
  File "<string>", line 1, in <module>
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "easyspider_executestage.py", line 688, in <module>
  File "commandline_config/commandline_config.py", line 107, in __init__
  File "commandline_config/commandline_config.py", line 139, in set_command_line
  File "commandline_config/commandline_config.py", line 201, in convert_type
AttributeError: Cannot convert [23] to type int
[1665] Failed to execute script 'easyspider_executestage' due to unhandled exception!

Cannot automatically check new version, please use the following command to check whether a new version avaliable and upgrade by pip: 
pip index versions commandline_config
pip install commandline --upgrade
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "easyspider_executestage.py", line 674, in clean
  File "easyspider_executestage.py", line 660, in saveData
TypeError: can only concatenate str (not "NoneType") to str
bill@billdeMacBook-Pro EasySpider_MacOS_all_arch % 
chrome 也替换过最新版本了，系统是13.4

**Comment by NaiboWang** [comment]
你在哪下载的软件版本？你现在执行的文件夹为v0.2.0或v0.3.0版本，但设计任务时用的是v0.3.1及以上版本，不兼容，是否同时下载过多个版本混合使用？
